require 'pry'
require 'httparty'
require 'json'
require 'colorize'
require 'awesome_print'

require_relative './Chef/cli'
require_relative './Chef/api'
require_relative './Chef/recipe'
require_relative './Chef/ingredient'